environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

cache:
  - '%LOCALAPPDATA%\Yarn\cache'

install:
  - ps: Install-Product node 8.9.1 x64

build_script:
  - yarn
  - .\node_modules\.bin\gulp electron
  - npm run compile

test_script:
  - node --version
  - .\scripts\test.bat
  - .\scripts\test-integration.bat
